# Generated by Django 6.0.4 on 2026-05-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
    ]
