# Generated by Django 6.0.4 on 2026-05-05 16:42

from django.db import migrations


def add_tags_column_if_missing(apps, schema_editor):
    table_name = "events"
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        table_names = connection.introspection.table_names(cursor)
        if table_name not in table_names:
            return

        columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, table_name)
        }

    if "tags" in columns:
        return

    # JSONField is stored as text in SQLite.
    schema_editor.execute(
        "ALTER TABLE events ADD COLUMN tags TEXT NOT NULL DEFAULT '[]'"
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_migration_2'),
    ]

    operations = [
        migrations.RunPython(add_tags_column_if_missing, noop_reverse),
    ]
