# Generated by Django 6.0.4 on 2026-05-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_fix_events_tags_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='max_participants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='participants',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
