# Generated by Django 6.0.4 on 2026-05-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_eventmodel_creator_alter_eventmodel_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
