# Generated by Django 6.0.4 on 2026-05-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_eventmodel_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
