# Generated by Django 6.0.4 on 2026-06-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_eventmodel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='description',
            new_name='detailed_description',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
